### ISSUE TITLE
Colorised invert not working

### ISSUE THREAD

**Issue by lahtis** [RodZill4/godot-procedural-textures#10]
Colorised invert not working in Ubuntu Linux.  When pressing black and white color. Color picker not show. Only blue popup window show. Colorize rainbow color picker working.

After a moment of reflection, I completely misunderstood. It works anyway. It is only slider. Not picker.

using: 0.6 version

**Comment by RodZill4** [comment]
Hmm maybe that gradient editor widget is not as intuitive as it should.
- Double clicking at the top of the widget will show a larger version (the blue popup), which is usefule to fine-tune the gradient.
- double-clicking on a cursor will open the color picker to modify the cursor's color
- double-clicking at the bottom will add a cursor
- right-clicking on a cursor will delete it (unless only 2 cursors are left)
If it does not work that way, it's a bug that shows only under Linux.

**Comment by lahtis** [comment]
I misunderstood the action. If that's what the action is about. It
working in Ubuntu Linux. Im closing the bug.

image of program.
https://mega.nz/#!opohhIJA!fIbPdFcFFXIif7sppyb2cJVy8py3fyCCUY1JEDShGJM

2019-10-16 23:00 UTC+03.00, Rodz Labs <notifications@github.com>:

**Comment by RodZill4** [comment]
Hmm there is a problem with the blue popup... It should not be that big...
