### ISSUE TITLE
Is there a Mac version of the one on itch?

### ISSUE THREAD

**Issue by wyattbiker** [RodZill4/godot-procedural-textures#12]
https://rodzilla.itch.io/material-maker/devlog/104409/material-maker-06

Thanks

**Comment by RodZill4** [comment]
Unfortunately I have no Mac to test. Would it be possible for you to run the export_plugin branch with Godot and tell me if there are any problems ? Thanks a lot !

**Comment by RodZill4** [comment]
Seems jackaperkins had some success on Mac.
