### ISSUE TITLE
Global UV scale option?

### ISSUE THREAD

**Issue by jackaperkins** [RodZill4/godot-procedural-textures#22]
Since all of the nodes read from a uv value for their calculations, it'd be nice if each material had a global UV scale value, starting at (1.0, 1.0) that could be adjusted independently of the nodes. It's frustrating to make a cool pattern with non symetric noise and then not be able to get a 2x2 version of it with unique quadrants. Would this be hard to implement?

**Comment by RodZill4** [comment]
I'm pretty sure it woud not work with the current implementation. Most shaders are written to generate seamless textures, and scaling UVs by 2 would generate 2x2 versions with identical quadrants. And transform shaders would completely break the result.

**Comment by jackaperkins** [comment]
Ahh I see, okay.
