### ISSUE TITLE
Add type hints to all GDScript files

### ISSUE THREAD

**Issue by Calinou** [RodZill4/godot-procedural-textures#30]
The codebase currently has some type hints, but many of them are missing (especially for function return types).

If you'd like, I could go through the codebase and add them. I just need to know whether you're OK with [type inference](https://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/static_typing.html#how-to-use-static-typing) (`:=`). I personally prefer using it, but I know some people don't :slightly_smiling_face:

**Comment by RodZill4** [comment]
I try to add types when modifying the code, but I started this project before types became available in Godot. I'm a C/C++ developper when I don't use Godot, so I'm kinda okayish with strong typing. ;)

**Comment by RodZill4** [comment]
I grep'd all missing return types and it seems the remaining ones cannot be fixed. Let's close this now (and be a bit more careful in the future).
