### ISSUE TITLE
Normal map filter always renders at 1024×1024 after loading a saved material

### ISSUE THREAD

**Issue by Calinou** [RodZill4/godot-procedural-textures#39]
While working on #38 (from commit https://github.com/RodZill4/godot-procedural-textures/commit/80f8071d7b6c630609e150c6fcb78ca5e72dbf22), I noticed that the normal map filter will always be render a 1024×1024 image after loading a material (even if the OptionButton says it's not 1024×1024).

This can be worked around by setting a different size in the OptionButton, which will cause the normal map to be rendered again. In comparison, this bug doesn't occur with the output material size.

**Comment by RodZill4** [comment]
Hmm it may be related to the Remote node. I have a few improvements for this node planned right after the convolution node update I'm doing ATM.

**Comment by RodZill4** [comment]
Seems this one is fixed now.
