### ISSUE TITLE
Add Godot 3.1 beta support?

### ISSUE THREAD

**Issue by me2beats** [RodZill4/godot-procedural-textures#4]
On 3 it's all right but on 3.1 I have 
> parser error method create node is not declared in the current class

**Comment by RodZill4** [comment]
Are you using the 0.5 release or master ? This looks like a problem I fixed with this commit: https://github.com/RodZill4/godot-procedural-textures/commit/7f4cc79a4777f819327e3734ff7c39b01d6ba3e2

**Comment by me2beats** [comment]
Just tried it from master and it seems to work)
