### ISSUE TITLE
Upload binary releases on GitHub for easier automated installation

### ISSUE THREAD

**Issue by Calinou** [RodZill4/godot-procedural-textures#72]
Using the [Godot BaseApp](https://github.com/flathub/org.godotengine.godot.BaseApp) I maintain, I'd like to create a Flatpak for Material Maker like I did for [Pixelorama](https://flathub.org/apps/details/com.orama_interactive.Pixelorama). To be able to do this, I need a download link that can be accessed in an automated manner (it must not expire over time). GitHub Releases can provide this, but not itch.io. A permanent link will also be useful to add Material Maker to [Scoop](https://scoop.sh/).

Could you upload the binary versions of the latest release to GitHub, please? Thanks in advance :slightly_smiling_face:

**Comment by RodZill4** [comment]
Is the .tgz file the package you need for Flatpak & Scoop ? Or just the exported Godot project ?

**Comment by Calinou** [comment]
@RodZill4 The easiest solution would be to upload the official Windows and Linux releases (I need the Windows one for Scoop, and the Linux one for Flatpak). I won't need the Linux binary to create the Flatpak (I only need the PCK), but it doesn't hurt to include it in the Linux release for consistency with the version on itch.io.

**Comment by RodZill4** [comment]
@Calinou Both files are now part of the release.

**Comment by Calinou** [comment]
@RodZill4 Thanks :slightly_smiling_face: I guess this issue can be closed now.
