### ISSUE TITLE
Make preview manually rotatable and preview texture scalable

### ISSUE THREAD

**Issue by Jummit** [RodZill4/godot-procedural-textures#9]
For convenience sake. The preview texture is so small it's almost useless.

**Comment by RodZill4** [comment]
Did you try to double-click the small 2d preview ?

I'm currently refactoring the whole addon in a separate branch, and it will take time before the result is usable again. Then I'll improve preview.

**Comment by Jummit** [comment]
> Did you try to double-click the small 2d preview ?

Yes, that's exactly what I'm looking for. Double clicking is a little bit undiscoverable, one click would work as well.

**Comment by RodZill4** [comment]
It's now possible to rotate the mesh and the camera in the 3d preview.
